### ISSUE TITLE
test failure with py27

### ISSUE THREAD

**Issue by ktdreyer** [alfredodeza/notario#8] opened 2016-02-04 21:46 UTC
I'm seeing the following test failure with Python 2.7 on CentOS 7:

```
+ py.test-2.7 -v notario/tests
============================= test session starts ==============================
platform linux2 -- Python 2.7.5 -- py-1.4.27 -- pytest-2.7.0 -- /usr/bin/python
rootdir: /builddir/build/BUILD/notario-0.0.8, inifile: 
collecting ... collected 198 items

notario/tests/test_decorators.py::TestInstanceOf::test_not_of_any_valid_types PASSED
notario/tests/test_decorators.py::TestInstanceOf::test_custom_valid_types PASSED
notario/tests/test_decorators.py::TestInstanceOf::test_custom_class PASSED
notario/tests/test_decorators.py::TestNotEmpty::test_not_of_any_valid_types PASSED
notario/tests/test_decorators.py::TestNotEmpty::test_not_empty_dict PASSED
notario/tests/test_decorators.py::TestNotEmpty::test_not_empty_str PASSED
notario/tests/test_decorators.py::TestNotEmpty::test_not_empty_list PASSED
notario/tests/test_decorators.py::TestNotEmpty::test_non_decorator_empty_string PASSED
notario/tests/test_decorators.py::TestNotEmpty::test_is_empty_delegates_to_validator PASSED
notario/tests/test_engine.py::TestEnforce::test_callable_failure_raises_invalid PASSED
notario/tests/test_engine.py::TestEnforce::test_callable_passes_with_flying_colors PASSED
notario/tests/test_engine.py::TestEnforce::test_equal_params_pass_with_flying_colors PASSED
notario/tests/test_engine.py::TestEnforce::test_unequal_params_raise_invalid PASSED
notario/tests/test_engine.py::TestEnforce::test_callable_with_messages_are_passed_on FAILED
notario/tests/test_engine.py::TestValidator::test_validate_top_level_keys PASSED
notario/tests/test_engine.py::TestValidator::test_validate_length_equality PASSED
notario/tests/test_engine.py::TestValidator::test_validate_length_equality_less_items PASSED
notario/tests/test_engine.py::TestValidator::test_validate_length_equality_returns PASSED
notario/tests/test_engine.py::TestValidator::test_validate_top_level_values PASSED
notario/tests/test_engine.py::TestValidator::test_validate_value_nested_dictionaries PASSED
notario/tests/test_engine.py::TestValidator::test_validate_key_doubly_nested_dictionaries PASSED
notario/tests/test_engine.py::TestValidator::test_validate_key_nested_dictionaries PASSED
notario/tests/test_engine.py::TestValidator::test_validate_value_nested_arrays PASSED
notario/tests/test_engine.py::TestValidator::test_validate_key_nested_arrays PASSED
notario/tests/test_engine.py::TestValidator::test_validate_multiple_items_as_values PASSED
notario/tests/test_engine.py::TestValidatorLeaves::test_traverser_returns_the_iterable_leaf_if_seen PASSED
notario/tests/test_engine.py::TestValidatorLeaves::test_traverser_returns_the_recursive_leaf_if_seen PASSED
notario/tests/test_engine.py::TestRecursiveValidator::test_bad_index_number PASSED
notario/tests/test_engine.py::TestRecursiveValidator::test_deal_with_recursion PASSED
notario/tests/test_engine.py::TestIterableValidator::test_not_enough_items_in_data PASSED
notario/tests/test_engine.py::TestIterableValidator::test_validate_nested_array_first PASSED
notario/tests/test_engine.py::TestIterableValidator::test_validate_nested_array PASSED
notario/tests/test_engine.py::TestIterableValidator::test_report_schema_errors PASSED
notario/tests/test_engine.py::TestIterableValidator::test_invalid_on_non_list PASSED
notario/tests/test_engine.py::TestOptionalKeys::test_optional_key_passes PASSED
notario/tests/test_engine.py::TestOptionalKeys::test_optional_key_raises PASSED
notario/tests/test_engine.py::TestValidate::test_refuses_non_dicts PASSED
notario/tests/test_exceptions.py::TestInvalid::test_include_the_key PASSED
notario/tests/test_exceptions.py::TestInvalid::test_include_the_path_in_str PASSED
notario/tests/test_exceptions.py::TestInvalid::test_include_the_key_in_str PASSED
notario/tests/test_exceptions.py::TestInvalid::test_multiple_keys_in_format_path PASSED
notario/tests/test_exceptions.py::TestInvalid::test_full_message PASSED
notario/tests/test_exceptions.py::TestInvalid::test_full_message_for_callable PASSED
notario/tests/test_exceptions.py::TestInvalid::test_full_message_for_value PASSED
notario/tests/test_exceptions.py::TestInvalid::test_full_message_for_callable_with_value PASSED
notario/tests/test_exceptions.py::TestSchemaError::test_reason_has_no_args PASSED
notario/tests/test_functional.py::TestValidate::test_simple_validation_against_empty_data PASSED
notario/tests/test_functional.py::TestValidate::test_most_simple_validation PASSED
notario/tests/test_functional.py::TestValidate::test_key_is_empty_string PASSED
notario/tests/test_functional.py::TestValidate::test_multi_pair_non_nested_last PASSED
notario/tests/test_functional.py::TestValidate::test_multi_pair_non_nested_first PASSED
notario/tests/test_functional.py::TestValidate::test_multi_pair_non_nested_second PASSED
notario/tests/test_functional.py::TestValidate::test_multi_pair_non_nested_third PASSED
notario/tests/test_functional.py::TestValidate::test_multi_pair_non_nested_last_key PASSED
notario/tests/test_functional.py::TestValidate::test_multi_pair_non_nested_first_key PASSED
notario/tests/test_functional.py::TestValidate::test_multi_pair_non_nested_second_key PASSED
notario/tests/test_functional.py::TestValidate::test_multi_pair_non_nested_third_key PASSED
notario/tests/test_functional.py::TestValidate::test_key_fails_before_value PASSED
notario/tests/test_functional.py::TestCherryPick::test_validate_only_one_item PASSED
notario/tests/test_functional.py::TestCherryPick::test_validate_custom_items PASSED
notario/tests/test_functional.py::TestCherryPick::test_complain_about_empty_must_validate PASSED
notario/tests/test_functional.py::TestHybrid::test_hybrid_delegates_when_dict_or_list PASSED
notario/tests/test_functional.py::TestHybrid::test_hybrid_delegates_when_dict_or_empty_list PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_all_items_pass PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_nested_can_raise_nested_invalid PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_nested_raises_nested_invalid PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_any_items_pass PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_all_items_fail PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_all_items_fail_length PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_all_items_fail_non_callable PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_any_items_fail PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_any_items_fail_non_callable PASSED
notario/tests/test_functional.py::TestWithIterableValidators::test_any_item_with_dictionaries PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_all_objects_pass PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_nested_raises_nested_invalid PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_all_objects_pass_with_hybrid PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_any_objects_pass PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_all_objects_fail PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_all_objects_fail_non_callable PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_all_objects_fail_length PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_any_object_fail PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_any_objects_fail_non_callable PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_no_pollution_from_previous_traversing_all_objects PASSED
notario/tests/test_functional.py::TestWithRecursiveValidators::test_no_pollution_from_previous_traversing_all_items PASSED
notario/tests/test_functional.py::TestChainableAllIn::test_all_items_pass PASSED
notario/tests/test_functional.py::TestChainableAllIn::test_one_item_fails PASSED
notario/tests/test_functional.py::TestChainableAnyIn::test_all_items_fail PASSED
notario/tests/test_functional.py::TestChainableAnyIn::test_one_item_passes PASSED
notario/tests/test_functional.py::TestOptional::test_optional_value PASSED
notario/tests/test_functional.py::TestOptional::test_optional_key PASSED
notario/tests/test_normal.py::TestSchema::test_return_data_structure_with_cero_index PASSED
notario/tests/test_normal.py::TestSchema::test_recurse_if_second_item_is_typle PASSED
notario/tests/test_normal.py::TestSchema::test_respect_more_than_two_values_in_tuple PASSED
notario/tests/test_normal.py::TestSchema::test_basic_key_value_pairs PASSED
notario/tests/test_regex.py::TestLinker::test_do_not_accept_non_pairs PASSED
notario/tests/test_regex.py::TestLinker::test_build_itself_with_same_amount_of_regexes PASSED
notario/tests/test_regex.py::TestLinker::test_assertion_error_for_failure PASSED
notario/tests/test_regex.py::TestLinker::test_assertion_error_has_message PASSED
notario/tests/test_regex.py::TestLinkerSequentially::test_fail_on_first_regex PASSED
notario/tests/test_regex.py::TestLinkerSequentially::test_fail_on_second_regex PASSED
notario/tests/test_regex.py::TestLinkerSequentially::test_fail_on_last_regex PASSED
notario/tests/test_regex.py::TestLinkerSequentially::test_fail_on_first_regex_with_prepending PASSED
notario/tests/test_regex.py::TestChain::test_prepend_with_multi_regex PASSED
notario/tests/test_regex.py::TestChain::test_dont_prepend_with_multi_regex PASSED
notario/tests/test_utils.py::TestIsCallable::test_is_callable PASSED
notario/tests/test_utils.py::TestIsCallable::test_is_not_callable PASSED
notario/tests/test_utils.py::TestOptionalDecorator::test_has_no_value PASSED
notario/tests/test_utils.py::TestOptionalDecorator::test_value PASSED
notario/tests/test_utils.py::TestOptionalDecorator::test_decorator_is_marked_as_optional PASSED
notario/tests/test_utils.py::TestOptionalDecorator::test_value_has_string PASSED
notario/tests/test_utils.py::TestSift::test_no_required_items PASSED
notario/tests/test_utils.py::TestSift::test_get_one_item_back PASSED
notario/tests/test_utils.py::TestReSort::test_keys_will_reset_to_zero PASSED
notario/tests/test_utils.py::TestIsEmpty::test_not_any_valid_structure_is_false PASSED
notario/tests/test_utils.py::TestIsEmpty::test_valid_structures_are_false_when_empty PASSED
notario/tests/test_utils.py::TestIsNestedTuple::test_is_nested_tuple PASSED
notario/tests/test_utils.py::TestIsNestedTuple::test_is_single_tuple PASSED
notario/tests/test_utils.py::TestIsNestedTuple::test_second_value_is_not_typle PASSED
notario/tests/test_utils.py::TestDataItem::test_return_key_from_ndict PASSED
notario/tests/test_utils.py::TestDataItem::test_return_key_from_non_ndict PASSED
notario/tests/test_utils.py::TestDataItem::test_return_first_item_in_list PASSED
notario/tests/test_utils.py::TestDataItem::test_fallback_to_repr_of_obj PASSED
notario/tests/test_utils.py::TestExpandSchema::test_not_delayed PASSED
notario/tests/test_utils.py::TestExpandSchema::test_is_delayed PASSED
notario/tests/test_utils.py::TestIsSchema::test_if_is_tuple PASSED
notario/tests/test_utils.py::TestIsSchema::test_is_delayed PASSED
notario/tests/test_utils.py::TestIsSchema::test_is_not_tuple PASSED
notario/tests/test_utils.py::TestEnsure::test_ensure PASSED
notario/tests/test_utils.py::TestEnsure::test_ensure_raises_assertionerror PASSED
notario/tests/validators/test_chainable.py::TestBasicChainValidator::test_complains_when_args_are_not_callable PASSED
notario/tests/validators/test_chainable.py::TestBasicChainValidator::test_assigns_validators_if_all_are_callable PASSED
notario/tests/validators/test_chainable.py::TestAllIn::test_all_validators_pass PASSED
notario/tests/validators/test_chainable.py::TestAllIn::test_a_validator_fails_with_a_tree_path PASSED
notario/tests/validators/test_chainable.py::TestAnyIn::test_all_validators_pass PASSED
notario/tests/validators/test_chainable.py::TestAnyIn::test_no_validator_passes PASSED
notario/tests/validators/test_cherry.py::TestCherryPick::test_single_pair_tuple PASSED
notario/tests/validators/test_cherry.py::TestCherryPick::test_single_items_tuples PASSED
notario/tests/validators/test_cherry.py::TestCherryPick::test_empty_tuple PASSED
notario/tests/validators/test_hybrid.py::TestHybrid::test_use_validator_passes PASSED
notario/tests/validators/test_hybrid.py::TestHybrid::test_use_validator_fails PASSED
notario/tests/validators/test_hybrid.py::TestHybrid::test_use_schema_passes PASSED
notario/tests/validators/test_hybrid.py::TestHybrid::test_use_schema_fails PASSED
notario/tests/validators/test_hybrid.py::TestFunctional::test_passes_single_value PASSED
notario/tests/validators/test_hybrid.py::TestFunctional::test_passes_object PASSED
notario/tests/validators/test_hybrid.py::TestFunctional::test_fail_object PASSED
notario/tests/validators/test_hybrid.py::TestFunctional::test_extra_unexpected_items PASSED
notario/tests/validators/test_iterables.py::TestAnyItem::test_any_item_fail PASSED
notario/tests/validators/test_iterables.py::TestAnyItem::test_tuple_schemas_cannot_run_on_single_values PASSED
notario/tests/validators/test_iterables.py::TestAnyItem::test_single_schemas_can_run_on_tuple_items PASSED
notario/tests/validators/test_iterables.py::TestAnyItem::test_any_item_pass PASSED
notario/tests/validators/test_iterables.py::TestAnyItem::test_any_item_pass_last_item PASSED
notario/tests/validators/test_iterables.py::TestAnyItem::test_any_item_fail_on_non_lists PASSED
notario/tests/validators/test_iterables.py::TestAnyItem::test_expecting_list_error PASSED
notario/tests/validators/test_iterables.py::TestAllItems::test_all_items_pass PASSED
notario/tests/validators/test_iterables.py::TestAllItems::test_all_items_fail_on_non_lists PASSED
notario/tests/validators/test_iterables.py::TestAllItems::test_expecting_list_error PASSED
notario/tests/validators/test_iterables.py::TestAllItems::test_all_items_fail PASSED
notario/tests/validators/test_iterables.py::TestAllItems::test_all_items_fail_last_item PASSED
notario/tests/validators/test_iterables.py::TestAllItems::test_all_items_fail_uses_first_invalid PASSED
notario/tests/validators/test_recursive.py::TestAllObjects::test_all_objects_fail PASSED
notario/tests/validators/test_recursive.py::TestAllObjects::test_all_objects_pass PASSED
notario/tests/validators/test_recursive.py::TestAnyObject::test_any_object_fail_all PASSED
notario/tests/validators/test_recursive.py::TestAnyObject::test_any_object_pass_first PASSED
notario/tests/validators/test_recursive.py::TestAnyObject::test_any_object_pass_second PASSED
notario/tests/validators/test_recursive.py::TestAnyObject::test_any_object_pass_last PASSED
notario/tests/validators/test_recursive.py::TestMultiSchema::test_pass_single_data_item PASSED
notario/tests/validators/test_recursive.py::TestMultiSchema::test_fail_on_non_callable PASSED
notario/tests/validators/test_recursive.py::TestMultiSchema::test_pass_two_data_items PASSED
notario/tests/validators/test_recursive.py::TestMultiSchema::test_pass_on_second_schema PASSED
notario/tests/validators/test_recursive.py::TestMultiSchema::test_fail_on_last_schema PASSED
notario/tests/validators/test_recursive.py::TestMultiSchema::test_pass_on_third_schema PASSED
notario/tests/validators/test_recursive.py::TestMultiSchema::test_pass_single_on_third_schema PASSED
notario/tests/validators/test_recursive.py::TestMultiSchema::test_fail_single_on_third_schema PASSED
notario/tests/validators/test_types.py::TestTypes::test_string_pass PASSED
notario/tests/validators/test_types.py::TestTypes::test_boolean_pass PASSED
notario/tests/validators/test_types.py::TestTypes::test_dictionary_pass PASSED
notario/tests/validators/test_types.py::TestTypes::test_array_pass PASSED
notario/tests/validators/test_types.py::TestTypes::test_integer_pass PASSED
notario/tests/validators/test_types.py::TestTypes::test_string_fail PASSED
notario/tests/validators/test_types.py::TestTypes::test_boolean_fail PASSED
notario/tests/validators/test_types.py::TestTypes::test_dictionary_fail PASSED
notario/tests/validators/test_types.py::TestTypes::test_array_fail PASSED
notario/tests/validators/test_types.py::TestTypes::test_integer_fail PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_string_pass PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_boolean_pass PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_dictionary_pass PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_array_pass PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_integer_pass PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_string_fail PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_boolean_fail PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_dictionary_fail PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_array_fail PASSED
notario/tests/validators/test_types.py::TestTypesAsDecorators::test_integer_fail PASSED
notario/tests/validators/test_types.py::TestTypesDelegating::test_string_decorated FAILED
notario/tests/validators/test_types.py::TestTypesDelegating::test_boolean_decorated FAILED
notario/tests/validators/test_types.py::TestTypesDelegating::test_dictionary_decorated FAILED
notario/tests/validators/test_types.py::TestTypesDelegating::test_array_decorated FAILED
notario/tests/validators/test_types.py::TestTypesDelegating::test_integer_fail FAILED

=================================== FAILURES ===================================
____________ TestEnforce.test_callable_with_messages_are_passed_on _____________

self = <notario.tests.test_engine.TestEnforce object at 0x150ad50>

    def test_callable_with_messages_are_passed_on(self):
        def callable_message(v): assert False, "this is completely False"
        with raises(Invalid) as exc:
            engine.enforce(1, callable_message, ['1'], 'key')
>       assert exc.value.reason == "this is completely False"
E       assert 'this is comp...\nassert False' == 'this is completely False'
E           this is completely False
E         - assert False

notario/tests/test_engine.py:36: AssertionError
__________________ TestTypesDelegating.test_string_decorated ___________________

self = <notario.tests.validators.test_types.TestTypesDelegating object at 0x154db50>

    def test_string_decorated(self):
        @types.string
        def validate(value):
            assert len(value) == 1, 'too long'
    
        with raises(AssertionError) as exc:
            validate('123')
>       assert exc.value.args[0] == 'too long'
E       assert "too long\nass... = len('123')" == 'too long'
E           too long
E         - assert 3 == 1
E         -  +  where 3 = len('123')

notario/tests/validators/test_types.py:146: AssertionError
__________________ TestTypesDelegating.test_boolean_decorated __________________

self = <notario.tests.validators.test_types.TestTypesDelegating object at 0x1746f50>

    def test_boolean_decorated(self):
        @types.boolean
        def validate(value):
            assert value is False, 'not false'
    
        with raises(AssertionError) as exc:
            validate(True)
>       assert exc.value.args[0] == 'not false'
E       assert 'not false\nas...True is False' == 'not false'
E           not false
E         - assert True is False

notario/tests/validators/test_types.py:155: AssertionError
________________ TestTypesDelegating.test_dictionary_decorated _________________

self = <notario.tests.validators.test_types.TestTypesDelegating object at 0x152b290>

    def test_dictionary_decorated(self):
        @types.dictionary
        def validate(value):
            assert len(value) == 1, 'too long'
    
        with raises(AssertionError) as exc:
            validate({'a': 1, 'b': 2})
>       assert exc.value.args[0] == 'too long'
E       assert "too long\nass...: 1, 'b': 2})" == 'too long'
E           too long
E         - assert 2 == 1
E         -  +  where 2 = len({'a': 1, 'b': 2})

notario/tests/validators/test_types.py:164: AssertionError
___________________ TestTypesDelegating.test_array_decorated ___________________

self = <notario.tests.validators.test_types.TestTypesDelegating object at 0x150ad10>

    def test_array_decorated(self):
        @types.array
        def validate(value):
            assert len(value) == 1, 'too long'
    
        with raises(AssertionError) as exc:
            validate([1, 2])
>       assert exc.value.args[0] == 'too long'
E       assert 'too long\nass...= len([1, 2])' == 'too long'
E           too long
E         - assert 2 == 1
E         -  +  where 2 = len([1, 2])

notario/tests/validators/test_types.py:173: AssertionError
____________________ TestTypesDelegating.test_integer_fail _____________________

self = <notario.tests.validators.test_types.TestTypesDelegating object at 0x16330d0>

    def test_integer_fail(self):
        @types.integer
        def validate(value):
            assert value == 1, 'too big'
    
        with raises(AssertionError) as exc:
            validate(3)
>       assert exc.value.args[0] == 'too big'
E       assert 'too big\nassert 3 == 1' == 'too big'
E           too big
E         - assert 3 == 1

notario/tests/validators/test_types.py:182: AssertionError
===================== 6 failed, 192 passed in 0.55 seconds =====================
```

**Comment by alfredodeza** [comment] 2016-02-05 01:05
Looking into it. Thanks for reporting it. Seem like the issue is generalized to other versions as well

**Comment by alfredodeza** [comment] 2016-02-05 01:09
So this is a `py.test` issue unfortunately. It is messing up the output of the errors because py.test itself uses assertions as well as Notario internally.  Once downgraded to 2.1.0 everything passed again.

This is not a good reason but a reason nonetheless! Will have it fixed asap.

**Comment by alfredodeza** [comment] 2016-02-05 13:53
All failures have now been fixed in master.

**Closed by alfredodeza** 2016-02-05 13:53 UTC
